schema = 1

[wrapper]
language = "python"
template_version = "0.0.0"

[runtime]
engine = "python"
version = "3.10"

[run]
entrypoint = ["python", "-m", "bot"]
source_dir = "user/src"

[submit]
include = [
  "user/src",
  "user/requirements.txt"
]
exclude = [
  "**/__pycache__/**",
  "**/*.pyc"
]
